/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.si400.view.swing;

import javax.swing.JButton;

/**
 *
 * @author Giovanni
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form SplashView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/si400/resources/menu.PNG"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setFocusable(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(0, 0, 300, 100);

        btnSair.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusable(false);
        jPanel1.add(btnSair);
        btnSair.setBounds(60, 400, 190, 50);

        btn1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn1.setText("Not implemented yet");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btn1.setContentAreaFilled(false);
        btn1.setFocusable(false);
        jPanel1.add(btn1);
        btn1.setBounds(60, 120, 190, 50);

        btn2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn2.setText("Not implemented yet");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btn2.setContentAreaFilled(false);
        btn2.setFocusable(false);
        jPanel1.add(btn2);
        btn2.setBounds(60, 190, 190, 50);

        btn3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn3.setText("Not implemented yet");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btn3.setContentAreaFilled(false);
        btn3.setFocusable(false);
        jPanel1.add(btn3);
        btn3.setBounds(60, 260, 190, 50);

        btn4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn4.setText("Not implemented yet");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btn4.setContentAreaFilled(false);
        btn4.setFocusable(false);
        jPanel1.add(btn4);
        btn4.setBounds(60, 330, 190, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 490);

        setSize(new java.awt.Dimension(316, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn1() {
        return btn1;
    }

    public JButton getBtn2() {
        return btn2;
    }

    public JButton getBtn3() {
        return btn3;
    }

    public JButton getBtn4() {
        return btn4;
    }

    public JButton getBtnSair() {
        return btnSair;
    }
}
