/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.si400.view;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Giovanni
 */
public class DataFilterView extends javax.swing.JFrame {

    /**
     * Creates new form SplashView
     */
    public DataFilterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        lbCountry = new javax.swing.JLabel();
        lbYear = new javax.swing.JLabel();
        lbSector = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();
        cbSector = new javax.swing.JComboBox<>();
        cbCountry = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnSair.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusable(false);
        jPanel1.add(btnSair);
        btnSair.setBounds(520, 470, 190, 50);

        lbCountry.setText("Country");
        jPanel1.add(lbCountry);
        lbCountry.setBounds(20, 30, 70, 17);

        lbYear.setText("Year");
        jPanel1.add(lbYear);
        lbYear.setBounds(20, 130, 60, 17);

        lbSector.setText("Sector");
        jPanel1.add(lbSector);
        lbSector.setBounds(20, 80, 70, 17);

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbYear);
        cbYear.setBounds(130, 130, 110, 27);

        cbSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbSector);
        cbSector.setBounds(130, 80, 350, 27);

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbCountry);
        cbCountry.setBounds(130, 30, 160, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 610);

        setSize(new java.awt.Dimension(735, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<String> cbSector;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbSector;
    private javax.swing.JLabel lbYear;
    // End of variables declaration//GEN-END:variables
    public JButton getBtnSair() {
        return btnSair;
    }

    public JComboBox<String> getCbYear() {
        return cbYear;
    }

    public JComboBox<String> getCbCountry() {
        return cbCountry;
    }

    public JComboBox<String> getCbSector() {
        return cbSector;
    }
}
