/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.si400.view;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Giovanni
 */
public class DataFilterView extends javax.swing.JFrame {

    /**
     * Creates new form SplashView
     */
    public DataFilterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        lbPais = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        lbSetor = new javax.swing.JLabel();
        cbAno = new javax.swing.JComboBox<>();
        cbSetor = new javax.swing.JComboBox<>();
        cbPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnSair.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusable(false);
        jPanel1.add(btnSair);
        btnSair.setBounds(520, 470, 190, 50);

        lbPais.setText("País");
        jPanel1.add(lbPais);
        lbPais.setBounds(20, 30, 70, 17);

        lbAno.setText("Ano");
        jPanel1.add(lbAno);
        lbAno.setBounds(20, 80, 60, 17);

        lbSetor.setText("Setor");
        jPanel1.add(lbSetor);
        lbSetor.setBounds(20, 130, 70, 17);

        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbAno);
        cbAno.setBounds(130, 80, 110, 27);

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbSetor);
        cbSetor.setBounds(130, 130, 350, 27);

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbPais);
        cbPais.setBounds(130, 30, 160, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 610);

        setSize(new java.awt.Dimension(735, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JComboBox<String> cbSetor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbSetor;
    // End of variables declaration//GEN-END:variables
    public JButton getBtnSair() {
        return btnSair;
    }

    public JComboBox<String> getCbAno() {
        return cbAno;
    }

    public JComboBox<String> getCbPais() {
        return cbPais;
    }

    public JComboBox<String> getCbSetor() {
        return cbSetor;
    }
}
